fixup! build: run ttnn tests as part of integration tests

diff --git a/.github/workflows/tt-metal-integration-tests.yml b/.github/workflows/tt-metal-integration-tests.yml
--- a/.github/workflows/tt-metal-integration-tests.yml
+++ b/.github/workflows/tt-metal-integration-tests.yml
@@ -75,8 +75,32 @@ jobs:
             -e PYTHONPATH=/workspace/tt-metal \
             ${DOCKER_IMAGE}:${IMAGE_HASH} \
             bash -c "
-              ./create_venv.sh && source ./python_env/bin/activate &&
-              ./build_metal.sh --build-metal-tests --build-ttnn-tests &&
-              TT_METAL_SLOW_DISPATCH_MODE=1 ./build_Release/test/tt_metal/unit_tests_llk &&
+              set -e  # Exit immediately if a command fails
+
+              # Set up the Python environment
+              if [ -z \"$PYTHON_ENV_DIR\" ]; then
+                  PYTHON_ENV_DIR=$(pwd)/python_env
+              fi
+              echo \"Creating virtual env in: $PYTHON_ENV_DIR\"
+              $PYTHON_CMD -m venv $PYTHON_ENV_DIR
+              source $PYTHON_ENV_DIR/bin/activate
+
+              # Install pip and dependencies
+              echo \"Forcefully using a version of pip that will work with our view of editable installs\"
+              pip install --force-reinstall pip==21.2.4
+              echo \"Setting up virtual env\"
+              python3 -m pip config set global.extra-index-url https://download.pytorch.org/whl/cpu
+              python3 -m pip install setuptools wheel==0.45.1
+              echo \"Installing dev dependencies\"
+              python3 -m pip install -r $(pwd)/tt_metal/python_env/requirements-dev.txt
+
+              # Install and build tt-metal
+              echo \"Installing tt-metal\"
+              pip install -e .
+              ./build_metal.sh --build-metal-tests --build-ttnn-tests
+
+              # Run tests
+              echo \"Running unit tests\"
+              # TT_METAL_SLOW_DISPATCH_MODE=1 ./build_Release/test/tt_metal/unit_tests_llk
               pytest tests/ttnn/unit_tests
             "
